config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'pages#index'

  resources :clients do
    resources :entreprises
    resources :immobiliers
    member do
      post :show, defaults: { format: :pdf }
    end
  end

  resources :cgps, only: [:show, :index] do
    resources :clients do
      post :show, on: :member, defaults: { format: :pdf }
      resources :entreprises do
        resources :immobiliers
      end
    end
  end

  resources :entreprises do
    member do
      get :cession
    end
    resources :immobiliers
  end

  resources :filiales do
    resources :immobiliers, only: [:destroy]
  end


end

app/models/immobilier.rb
class Immobilier < ApplicationRecord
  belongs_to :proprietable, polymorphic: true

end

app/controllers/immobiliers_controller.rb
class ImmobiliersController < ApplicationController
  def new
    @client = Client.find(params[:client_id])
    @immobilier = @client.immobiliers.build
  end

  def create
    @proprietable = if params[:proprietable_type] == 'Entreprise'
                      Entreprise.find(params[:proprietable_id])
                    else
                      Client.find(params[:client_id])
                    end

    @immobilier = @proprietable.immobiliers.build(immobilier_params)

    if @immobilier.save
      # Redirige vers la page du client associé
      client = @proprietable.is_a?(Client) ? @proprietable : @proprietable.client
      redirect_to client_path(client), notice: 'Bien immobilier ajouté avec succès.'
    else
      render :new
    end
  end

  def destroy
    @immobilier = Immobilier.find(params[:id])
    client = @immobilier.proprietable_type == 'Client' ? @immobilier.proprietable : @immobilier.proprietable.client
    @immobilier.destroy
    redirect_to client_path(client), notice: 'Bien immobilier supprimé avec succès.'
  end

  def edit
    @client = Client.find(params[:client_id])
    @immobilier = Immobilier.find(params[:id])
  end

def update
  @immobilier = Immobilier.find(params[:id])

  if @immobilier.update(immobilier_params)
    # Redirige vers la page du client associé
    client = @immobilier.proprietable_type == 'Client' ? @immobilier.proprietable : @immobilier.proprietable.client
    redirect_to client_path(client), notice: 'Bien immobilier mis à jour avec succès.'
  else
    render :edit
  end
end



  private

  def immobilier_params
    params.require(:immobilier).permit(:designation, :date_acquisition, :valeur_acquisition, :taux_detention, :valeur_actuelle, :type_detention, :proprietable_type, :proprietable_id)
  end

end

app/views/immobiliers/edit.html.erb
<%= form_with(model: [@client, @immobilier], local: true) do |form| %>
  <% if @immobilier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@immobilier.errors.count, "error") %> prevented this immobilier from being saved:</h2>
      <ul>
        <% @immobilier.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :designation %>
    <%= form.text_field :designation %>
  </div>

  <div class="field">
    <%= form.label :date_acquisition %>
    <%= form.date_select :date_acquisition, start_year: 1960 %>
  </div>

  <div class="field">
    <%= form.label :valeur_acquisition %>
    <%= form.number_field :valeur_acquisition %>
  </div>

  <div class="field">
    <%= form.label :taux_detention, 'Taux de détention (%)' %>
    <%= form.number_field :taux_detention %>
  </div>

  <div class="field">
    <%= form.label :valeur_actuelle %>
    <%= form.number_field :valeur_actuelle %>
  </div>

  <div class="field">
    <%= form.label :type_detention %>
    <%= form.select :type_detention, ['Pleine propriété', 'Nue-propriété', 'Usufruit'], { include_blank: 'Sélectionnez le type de détention' } %>
  </div>

  <%= form.submit 'Enregistrer les modifications' %>
<% end %>

app/views/immobiliers/new.html.erb
<%= form_with(model: @immobilier, url: client_immobiliers_path(client_id: params[:client_id], proprietable_type: params[:proprietable_type], proprietable_id: params[:proprietable_id]), local: true) do |form| %>
  <% if @immobilier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@immobilier.errors.count, "error") %> prevented this immobilier from being saved:</h2>
      <ul>
        <% @immobilier.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :designation %>
    <%= form.text_field :designation %>
  </div>

  <div class="field">
    <%= form.label :date_acquisition %>
    <%= form.date_select :date_acquisition %>
  </div>

  <div class="field">
    <%= form.label :valeur_acquisition %>
    <%= form.number_field :valeur_acquisition %>
  </div>

  <div class="field">
    <%= form.label :taux_detention, 'Taux de détention (%)' %>
    <%= form.number_field :taux_detention %>
  </div>

  <div class="field">
    <%= form.label :valeur_actuelle %>
    <%= form.number_field :valeur_actuelle %>
  </div>

  <div class="field">
    <%= form.label :type_detention %>
    <%= form.select :type_detention, ['Pleine propriété', 'Nue-propriété', 'Usufruit'], { include_blank: 'Sélectionnez le type de détention' } %>
  </div>

  <%= form.submit 'Enregistrer le bien immobilier' %>
<% end %>