config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'pages#index'

  resources :clients do
    resources :entreprises
    resources :immobiliers
    member do
      post :show, defaults: { format: :pdf }
    end
  end

  resources :cgps, only: [:show, :index] do
    resources :clients do
      post :show, on: :member, defaults: { format: :pdf }
      resources :entreprises do
        resources :immobiliers
      end
    end
  end

  resources :entreprises do
    member do
      get :cession
    end
    resources :immobiliers
  end

  resources :filiales do
    resources :immobiliers, only: [:destroy]
  end


end

app/models/client.rb
class Client < ApplicationRecord
  has_many :entreprises
  belongs_to :cgp
  has_many :immobiliers, as: :proprietable
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  def index
    @clients = Client.all
  end

  def show
    @client = Client.find(params[:id])
    @cgp = @client.cgp
    @entreprises = @client.entreprises.includes(:immobiliers)

    # Nouvelle variable pour l'organigramme
    @organigramme_data = prepare_organigramme_data(@client.entreprises)
    @immobiliers = @client.immobiliers + Immobilier.where(proprietable: @client.entreprises)

    respond_to do |format|
      format.html
      format.pdf do
        @image_uri = params[:image_uri]
        if @image_uri.blank?
          Rails.logger.debug "Image URI is missing"
        end
        render pdf: "Rapport_Client",
               template: "clients/rapport_pdf", # Assurez-vous que ce fichier existe
               layout: false, # Pas de layout ou spécifiez un layout si nécessaire
               formats: [:html], # Spécifiez le format du template
               encoding: 'UTF-8'
      end
    end

  end

  def new
    @cgp = Cgp.find(params[:cgp_id])
    @client = @cgp.clients.build
  end


  def edit
    @client = Client.find(params[:id])
  end

  def create
    @cgp = Cgp.find(params[:cgp_id])
    @client = @cgp.clients.build(client_params)
    if @client.save
      redirect_to cgp_client_path(@cgp, @client)
    else
      render :new
    end
  end


  def update
    @client = Client.find(params[:id])
    if @client.update(client_params)
      redirect_to @client
    else
      render :edit
    end
  end

  def destroy
    @client = Client.find(params[:id])
    @client.destroy
    redirect_to clients_url
  end

  private

  def prepare_organigramme_data(entreprises)
    entreprises.map do |entreprise|
      {
        id: entreprise.id,
        nom: entreprise.nom,
        entreprise_mere_id: entreprise.entreprise_mere_id,
        taux_detention: entreprise.taux_detention,
        filiales: prepare_organigramme_data(entreprise.filiales)
      }
    end
  end
    def client_params
      params.require(:client).permit(:cgp_id, :nom, :prenom, :date_naissance, :situation_matrimoniale, :regime_matrimonial, :presence_enfants, :civilite, :email, :telephone_principal, :telephone_secondaire, :adresse, :code_postal, :ville)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/new.html.erb
<%= form_with(model: [@cgp, @client], local: true) do |form| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prevented this client from being saved:</h2>
      <ul>
        <% @client.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :nom %>
  <%= form.text_field :nom %>

  <%= form.label :prenom %>
  <%= form.text_field :prenom %>

  <%= form.label :date_naissance %>
  <%= form.date_select :date_naissance %>

<%= form.label :situation_matrimoniale %>
<%= form.select :situation_matrimoniale, options_for_select(['marié', 'célibataire', 'divorcé', 'veuf', 'union libre', 'pacsé']), { include_blank: 'Sélectionnez' } %>


<%= form.label :regime_matrimonial %>
<%= form.select :regime_matrimonial, options_for_select([
  'Aucun',
  'Régime légal à compter du 01/02/1966',
  'Communauté réduite aux acquêts',
  'Communauté universelle',
  'Régime légal avant le 01/02/1966',
  'Communauté de meubles et d'acquêts',
  'Séparation de biens',
  'Participation aux acquêts',
  'Séparation de biens avec société d'acquêts',
  'Régime optionnel de participation aux acquêts'
]), { include_blank: 'Sélectionnez' } %>


  <%= form.label :presence_enfants %>
  <%= form.check_box :presence_enfants %>

  <%= form.label :civilite %>
  <%= form.select :civilite, ['Monsieur', 'Madame', 'Autre'] %>

  <%= form.label :email %>
  <%= form.email_field :email %>

  <%= form.label :telephone_principal %>
  <%= form.telephone_field :telephone_principal %>

  <%= form.label :telephone_secondaire %>
  <%= form.telephone_field :telephone_secondaire %>

  <%= form.label :adresse %>
  <%= form.text_area :adresse %>

  <%= form.label :code_postal %>
  <%= form.text_field :code_postal %>

  <%= form.label :ville %>
  <%= form.text_field :ville %>


  <%= form.submit "Enregistrer le client" %>
<% end %>

app/views/clients/rapport_pdf.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rapport Client</title>
  <!-- Styles supplémentaires ici si nécessaire -->
</head>
<body>
  <h1>Rapport pour <%= @client.nom %> <%= @client.prenom %></h1>

  <!-- Assurez-vous que @image_uri est défini et non vide -->
  <% if @image_uri.present? %>
  <img src="<%= @image_uri %>" alt="Organigramme" style="width: 100%; height: auto;">
<% else %>
  <p>L'image de l'organigramme n'est pas disponible.</p>
<% end %>


  <!-- Autres contenus de votre rapport ici -->
</body>
</html>

app/views/clients/show.html.erb
<div class="container mx-auto p-6">

<h1>Informations du Client</h1>

<p>
  <strong>Nom :</strong>
  <%= @client.nom %>
</p>

<p>
  <strong>Prénom :</strong>
  <%= @client.prenom %>
</p>

<p>
  <strong>Date de Naissance :</strong>
  <%= @client.date_naissance %>
</p>

<p>
  <strong>Situation Matrimoniale :</strong>
  <%= @client.situation_matrimoniale %>
</p>

<p>
  <strong>Régime Matrimonial :</strong>
  <%= @client.regime_matrimonial %>
</p>

<p>
  <strong>Présence Enfants :</strong>
  <%= @client.presence_enfants ? 'Oui' : 'Non' %>
</p>

<p>
  <strong>Civilité :</strong>
  <%= @client.civilite %>
</p>

<p>
  <strong>Email :</strong>
  <%= @client.email %>
</p>

<p>
  <strong>Téléphone Principal :</strong>
  <%= @client.telephone_principal %>
</p>

<p>
  <strong>Téléphone Secondaire :</strong>
  <%= @client.telephone_secondaire %>
</p>

<p>
  <strong>Adresse :</strong>
  <%= @client.adresse %>
</p>

<p>
  <strong>Code Postal :</strong>
  <%= @client.code_postal %>
</p>

<p>
  <strong>Ville :</strong>
  <%= @client.ville %>
</p>
<%= link_to 'Ajouter une entreprise', new_cgp_client_entreprise_path(@cgp, @client), class: 'inline-block px-6 py-2 text-white font-bold bg-green-500 hover:bg-green-700 rounded' %>

<%= link_to 'Ajouter un bien immobilier pour le client', new_client_immobilier_path(@client), class: 'inline-block px-6 py-2 text-white font-bold bg-orange-500 hover:bg-orange-700 rounded' %>

<div id="organigramme" ></div>
 <!-- Div pour l'organigramme -->

<%= form_with url: cgp_client_path(@cgp, @client, format: :pdf), method: :post do |form| %>
  <%= form.hidden_field :image_uri, id: 'image_uri_field' %>
  <%= form.submit 'Générer le PDF', class: 'bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded' %>
<% end %>


<h2 class="text-4xl font-bold text-gray-800 mt-6 mb-4">Biens immobiliers de <%= @client.nom %> <%= @client.prenom %></h2>

<table class="min-w-full table-auto">
  <thead class="justify-between">
    <tr class="bg-gray-800">
      <th class="px-16 py-2">
        <span class="text-gray-300">Désignation</span>
      </th>
      <th class="px-16 py-2">
        <span class="text-gray-300">Date d'Acquisition</span>
      </th>
      <th class="px-16 py-2">
        <span class="text-gray-300">Valeur Acquisition</span>
      </th>
      <th class="px-16 py-2">
        <span class="text-gray-300">Taux de Détention (%)</span>
      </th>
      <th class="px-16 py-2">
        <span class="text-gray-300">Valeur Actuelle</span>
      </th>
      <th class="px-16 py-2">
        <span class="text-gray-300">Type de Détention</span>
      </th>
      <th class="px-16 py-2">
        <span class="text-gray-300">Action</span>
      </th>
    </tr>
  </thead>
  <tbody class="bg-gray-200">
    <% @client.immobiliers.each do |immobilier| %>
      <tr class="bg-white border-4 border-gray-200">
        <td class="px-16 py-2 flex flex-row items-center">
          <%= immobilier.designation %>
        </td>
        <td class="px-16 py-2">
          <%= immobilier.date_acquisition %>
        </td>
        <td class="px-16 py-2">
          <%= immobilier.valeur_acquisition %> €
        </td>
        <td class="px-16 py-2">
          <%= immobilier.taux_detention %>
        </td>
        <td class="px-16 py-2">
          <%= immobilier.valeur_actuelle %> €
        </td>
        <td class="px-16 py-2">
          <%= immobilier.type_detention %>
        </td>
          <td>
<div class="flex items-center space-x-4">
  <%= form_with url: client_immobilier_path(@client, immobilier), method: :delete do %>
    <%= submit_tag 'Supprimer', data: { turbo_confirm: 'Êtes-vous sûr ?', turbo_method: :delete }, class: 'bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded' %>
  <% end %>

  <%= link_to 'Éditer', edit_client_immobilier_path(@client, immobilier), class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded' %>
</div>

    </td>
      </tr>
    <% end %>
  </tbody>
</table>

<h2 class="text-4xl font-bold text-gray-800 mt-6 mb-4">
  Entreprises de <%= @client.nom %> <%= @client.prenom %>
</h2>

<table class="min-w-full leading-normal shadow-md rounded-lg overflow-hidden">
  <thead class="bg-gray-800 text-white">
    <tr>
      <th class="py-3 px-6">Nom</th>
      <th class="py-3 px-6">Forme Juridique</th>
      <th class="py-3 px-6">Activité</th>
      <th class="py-3 px-6">Capital Social</th>
      <th class="py-3 px-6">Valeur Estimée</th>
      <th class="py-3 px-6">Date de Création</th>
      <th class="py-3 px-6">Date d'Acquisition</th>
      <th class="py-3 px-6">Taux de Détention</th>
      <th class="py-3 px-6">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @entreprises.where(entreprise_mere_id: nil).each do |entreprise| %>
      <tr class="bg-white border-b border-gray-200">
        <td class="py-4 px-6"><%= entreprise.nom %></td>
        <td class="py-4 px-6"><%= entreprise.forme_juridique %></td>
        <td class="py-4 px-6"><%= entreprise.activite %></td>
        <td class="py-4 px-6"><%= entreprise.capital_social %></td>
        <td class="py-4 px-6"><%= entreprise.valeur_estimee %></td>
        <td class="py-4 px-6"><%= entreprise.date_creation %></td>
        <td class="py-4 px-6"><%= entreprise.date_acquisition %></td>
        <td class="py-4 px-6"><%= entreprise.taux_detention %>%</td>
    <td class="py-4 px-6 text-right">
  <div class="flex flex-col space-y-2 sm:flex-row sm:space-y-0 sm:space-x-2">
    <%= link_to 'Éditer', edit_cgp_client_entreprise_path(@cgp, @client, entreprise), class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded transition duration-300 ease-in-out' %>
    <%= link_to '+filiale', new_cgp_client_entreprise_path(@cgp, @client, entreprise_mere_id: entreprise.id), class: 'bg-purple-500 hover:bg-purple-700 text-white font-bold py-2 px-4 rounded transition duration-300 ease-in-out' %>
    <%= link_to '+immobilier', new_client_immobilier_path(client_id: @client.id, proprietable_type: 'Entreprise', proprietable_id: entreprise.id), class: 'bg-orange-500 hover:bg-orange-700 text-white font-bold py-2 px-4 rounded transition duration-300 ease-in-out' %>
  </div>
</td>

      </tr>
 <% if entreprise.immobiliers.any? %>
  <% entreprise.immobiliers.each do |immobilier| %>
    <tr class="bg-blue-100">
      <td colspan="8">

        <table class="min-w-full">
          <tr>
            <td>Designation: <%= immobilier.designation %></td>
            <td>Date Acquisition: <%= immobilier.date_acquisition %></td>
            <td>Valeur Acquisition: <%= immobilier.valeur_acquisition %>€</td>
            <td>Taux Détention: <%= immobilier.taux_detention %>%</td>
            <td>Type Détention: <%= immobilier.type_detention %></td>
            <td>Valeur Actuelle: <%= immobilier.valeur_actuelle %>€</td>
          </tr>
        </table>
      </td>
      <td class="text-right">
        <div class="flex justify-end items-center space-x-2">
          <%= link_to 'Éditer', edit_client_immobilier_path(client_id: @client.id, id: immobilier.id), class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded' %>
          <%= form_with url: entreprise_immobilier_path(entreprise, immobilier), method: :delete do %>
            <%= submit_tag 'Supprimer', data: { confirm: 'Êtes-vous sûr ?', turbo: false }, class: 'bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded' %>
          <% end %>
        </div>
      </td>
    </tr>
  <% end %>
<% end %>

      <% entreprise.filiales.each do |filiale| %>
        <tr class="bg-gray-100">
    <td class="py-3 px-6">Filiale <%= filiale.nom %></td>
    <td class="py-3 px-6"><%= filiale.forme_juridique %></td>
    <td class="py-3 px-6"><%= filiale.activite %></td>
    <td class="py-3 px-6"><%= filiale.capital_social %></td>
    <td class="py-3 px-6"><%= filiale.valeur_estimee %> €</td>
    <td class="py-3 px-6"><%= filiale.date_creation %></td>
    <td class="py-3 px-6"><%= filiale.date_acquisition %></td>
    <td class="py-3 px-6"><%= filiale.taux_detention %>%</td>
<td class="py-3 px-6 text-right">
  <div class="flex space-x-2">
    <%= link_to 'Éditer', edit_cgp_client_entreprise_path(@cgp, @client, filiale), class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded transition duration-300 ease-in-out' %>
    <%= link_to '+ bien immobilier', new_client_immobilier_path(client_id: @client.id, proprietable_type: 'Entreprise', proprietable_id: filiale.id), class: 'bg-orange-500 hover:bg-orange-700 text-white font-bold py-2 px-4 rounded ml-2 transition duration-300 ease-in-out' %>
    <%= link_to 'Cession', cession_entreprise_path(filiale), class: 'bg-yellow-500 hover:bg-yellow-700 text-white font-bold py-2 px-4 rounded' %>
  </div>
</td>

  </tr>
<% if filiale.immobiliers.any? %>
  <% filiale.immobiliers.each do |immobilier_filiale| %>
    <tr class="bg-green-100">
      <td colspan="8" class="py-2 px-4">
        <table class="min-w-full">
          <tbody>
            <tr>
              <td>Designation: <%= immobilier_filiale.designation %></td>
              <td>Date Acquisition: <%= immobilier_filiale.date_acquisition %></td>
              <td>Valeur Acquisition: <%= immobilier_filiale.valeur_acquisition %>€</td>
              <td>Taux Détention: <%= immobilier_filiale.taux_detention %>%</td>
              <td>Type Détention: <%= immobilier_filiale.type_detention %></td>
              <td>Valeur Actuelle: <%= immobilier_filiale.valeur_actuelle %>€</td>
            </tr>
          </tbody>
        </table>
      </td>
      <td class="py-2 px-4 text-right">
        <div class="flex justify-end items-center space-x-2">
          <%= link_to 'Éditer', edit_client_immobilier_path(client_id: @client.id, id: immobilier_filiale.id), class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded' %>
          <%= form_with url: entreprise_immobilier_path(filiale, immobilier_filiale), method: :delete do %>
            <%= submit_tag 'Supprimer', data: { confirm: 'Êtes-vous sûr ?', turbo: false }, class: 'bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded' %>
          <% end %>
        </div>
      </td>
    </tr>
  <% end %>
<% end %>

      <% end %>
    <% end %>
  </tbody>
</table>
</div>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.3.2/html2canvas.min.js"></script>

<script type="text/javascript">
  var immobiliersData = <%= @immobiliers.to_json.html_safe %>;
</script>
<script type="text/javascript">
  google.charts.load('current', {packages:["orgchart"]});
  google.charts.setOnLoadCallback(drawChart);

  function drawChart() {
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Name');
    data.addColumn('string', 'Manager');

    // Ajouter le client comme racine
    data.addRows([
      [{v:'client_<%= @client.id %>', f:'<%= @client.nom %> <%= @client.prenom %>'}, '']
    ]);

    // Fonction récursive pour traiter les entreprises et leurs filiales
    function addEntreprises(entreprises, parentId) {
      entreprises.forEach(function(entreprise) {
        var entrepriseId = 'entreprise_' + entreprise.id;
        var parent = parentId ? 'entreprise_' + parentId : 'client_<%= @client.id %>';
        var nomEntreprise = entreprise.nom;

        // Formatage pour mettre le taux de détention au-dessus du nom de l'entreprise
        var displayText = '<div>' + (entreprise.taux_detention ? '<strong>' + entreprise.taux_detention + '%</strong><br>' : '') + nomEntreprise + '</div>';
        data.addRows([[{v: entrepriseId, f: displayText}, parent]]);

        // Ajouter les filiales, le cas échéant
        if (entreprise.filiales && entreprise.filiales.length > 0) {
          addEntreprises(entreprise.filiales, entreprise.id);
        }
      });
    }

    // Ajouter les biens immobiliers
     // Utiliser immobiliersData pour ajouter les biens immobiliers
immobiliersData.forEach(function(immobilier) {
  var proprietableId = immobilier.proprietable_type == 'Client' ? 'client_<%= @client.id %>' : 'entreprise_' + immobilier.proprietable_id;
  var cellContent = '<div style="background-color: #f5f5dc; padding: 5px; border-radius: 5px;">' + immobilier.designation + ' </div>';

  data.addRows([[{
    v: 'immobilier_' + immobilier.id,
    f: cellContent
  }, proprietableId]]);
});

    // Appeler la fonction récursive avec les entreprises du client
    addEntreprises(<%= @organigramme_data.to_json.html_safe %>);

    // Options pour agrandir l'organigramme
    var options = {
      allowHtml: true,
      size: 'large', // Agrandit la taille des boîtes et du texte
      width: '100%',
      height: 800 // Ajustez cette valeur pour changer la hauteur
    };

    var chart = new google.visualization.OrgChart(document.getElementById('organigramme'));

// Attacher l'événement 'ready' avant de dessiner le graphique
google.visualization.events.addListener(chart, 'ready', function () {
  console.log("Organigramme prêt pour la capture");

  // Définir un délai pour s'assurer que le graphique est complètement rendu
 setTimeout(function() {
  var organigrammeElement = document.getElementById("organigramme");
  organigrammeElement.style.width = '2000px'; // Augmenter la largeur
  organigrammeElement.style.height = '2000px'; // Augmenter la hauteur

  html2canvas(organigrammeElement).then(canvas => {
    var imgUri = canvas.toDataURL("image/png");
    document.getElementById('image_uri_field').value = imgUri;
  });

  // Remettre la taille originale après la capture
  organigrammeElement.style.width = '';
  organigrammeElement.style.height = '';
}, 1000); // Un délai de 1000 millisecondes
});

// Dessiner le graphique
chart.draw(data, options);


  }
</script>

app/views/clients/test_pdf.html.erb
<!DOCTYPE html>
<html>
  <body>
    <h1>Test PDF</h1>
  </body>
</html>